name: Continuous Integration

on:
  pull_request: {}

concurrency:
  group: continuous_integration-${{ github.head_ref }} # current working branch
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  test_passed:
    needs: [test]
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

